src/Entity/Trick.php
<?php

namespace App\Entity;

use App\Repository\CommentaryRepository;
use App\Repository\MediaRepository;
use App\Repository\TrickRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TrickRepository::class)]
class Trick
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, unique: true)]
    private ?string $name = null;

    #[ORM\Column(type: 'text', length: 65535)]
    private ?string $description = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $publishedDate = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $lastUpdated = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(name : 'group_id', nullable: false)]
    private ?Group $group = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $User = null;

    #[ORM\OneToMany(mappedBy: 'trick', targetEntity: Media::class, orphanRemoval: true, cascade: ['persist', 'remove'])]
    private Collection $medias;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    private ?Media $mainMedia = null;

    #[ORM\OneToMany(mappedBy: 'trick', targetEntity: Commentary::class, orphanRemoval: true, cascade: ['persist', 'remove'])]
    private Collection $commentaries;

    #[ORM\Column(length: 255)]
    private string $slug;
    
    public function __construct()
    {
        $this->medias = new ArrayCollection();
        $this->commentaries = new ArrayCollection();
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;
        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;
        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPublishedDate(): ?\DateTimeInterface
    {
        return $this->publishedDate;
    }

    public function setPublishedDate(\DateTimeInterface $publishedDate): self
    {
        $this->publishedDate = $publishedDate;

        return $this;
    }

    public function getLastUpdated(): ?\DateTimeInterface
    {
        return $this->lastUpdated;
    }

    public function setLastUpdated(?\DateTimeInterface $lastUpdated): self
    {
        $this->lastUpdated = $lastUpdated;

        return $this;
    }

    public function getGroup(): ?Group
    {
        return $this->group;
    }

    public function setGroup(?Group $group): self
    {
        $this->group = $group;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }

    /**
     * @return Collection<int, Media>
     */
    public function getMedias(): Collection
    {
        return $this->medias;
    }

    public function addMedia(Media $media): self
    {
        if (!$this->medias->contains($media)) {
            $this->medias->add($media);
            $media->setTrick($this);
        }

        return $this;
    }

    public function removeMedia(Media $media): self
    {
        if ($this->medias->removeElement($media)) {
            // set the owning side to null (unless already changed)
            if ($media->getTrick() === $this) {
                $media->setTrick(null);
            }
        }

        return $this;
    }

    public function getMainMedia(): ?Media
    {
        return $this->mainMedia;
    }

    public function setMainMedia(?Media $mainMedia): self
    {
        $this->mainMedia = $mainMedia;

        return $this;
    }

    /**
     * @return Collection<int, Commentary>
     */
    public function getCommentaries(): Collection
    {
        return $this->commentaries;
    }

    public function purgeTrick( CommentaryRepository $commentaryRepository, MediaRepository $mediaRepository): bool
    {
        foreach($this->commentaries as $commentary) {
            $commentaryRepository->remove($commentary, true);
        }
        foreach($this->medias as $media) {
            $mediaRepository->remove($media, true);
        }
        return true;
    }

    public function addCommentary(Commentary $commentary): self
    {
        if (!$this->commentaries->contains($commentary)) {
            $this->commentaries->add($commentary);
            $commentary->setTrick($this);
    }

        return $this;
    }

    public function removeCommentary(Commentary $commentary): self
    {
        if ($this->commentaries->removeElement($commentary)) {
            // set the owning side to null (unless already changed)
            if ($commentary->getTrick() === $this) {
                $commentary->setTrick(null);
            }
        }

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $username = null;

    #[ORM\Column]
    private ?bool $isValidated = null;

    #[ORM\Column]
    private ?string $Avatar = null;

    #[ORM\OneToOne(mappedBy: 'user', orphanRemoval: true, cascade: ['persist', 'remove'])]
    private ?Token $token = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getusername(): ?string
    {
        return $this->username;
    }

    public function setusername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getIsValidated(): ?bool
    {
        return $this->isValidated;
    }

    public function setIsValidated(bool $isValidated): self
    {
        $this->isValidated = $isValidated;

        return $this;
    }

    public function getAvatar(): ?string
    {
        return $this->Avatar;
    }

    public function setAvatar(string $Avatar): self
    {
        $this->Avatar = $Avatar;

        return $this;
    }

    public function getToken(): ?Token
    {
        return $this->token;
    }

    public function setToken(Token $token): self
    {
        // set the owning side of the relation if necessary
        if ($token->getUser() !== $this) {
            $token->setUser($this);
        }

        $this->token = $token;

        return $this;
    }

}

src/Form/TrickType.php
<?php

namespace App\Form;

use App\Entity\Group;
use App\Entity\Trick;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\EventDispatcher\Attribute\AsEventListener;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TrickType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        
        $builder
            ->add('name')
            ->add('images', FileType::class, [
                'label' => false,
                'multiple' => true,
                'mapped' => false,
                'required' => false,
                'attr' => [
                    'class' => 'trick_images',
                ],
            ])
            ->add('videos', CollectionType::class, [
                'entry_type' => UrlType::class,
                'entry_options' => [
                    'attr' => ['class' => 'mb-2'],
                ],
                'allow_add' => true,
                'label' => false,
                'required' => false,
                'mapped' => false,
            ])
            ->add('description', TextareaType::class, [
                'label' => false,
                'attr' => [
                    'placeholder' => "Description",
                ],
            ])
            ->add('group', EntityType::class, [
                'label' => 'Group',
                'class' => Group::class,
                'choice_label' => 'name'
            ])
            ->add('count', HiddenType::class, [
                'mapped' => false,
            ])
            ->add('Create_Trick', SubmitType::class);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Trick::class,
        ]);
    }
    

}

templates/trick/_commentarys.html.twig
<div class="row shadow-sm m-3" id="Commentary_{{ commentary.id }}">
	<div class="col col-1 mx-3">
	<div class="row row-cols-1">
		<img src={{ asset(avatars_directory ~ commentary.user.avatar) }} class="bd-placeholder-img card-img-top" width="32" height="32" alt="image"/>
		{{ commentary.user.Username }}
		<br>
		{{ commentary.publishedDate|date('Y-m-d') }}
		
	</div>
	</div>
	<div class="col">
	<div class="row">
	</div>
		<p>{{ commentary.commentary }}</p>
	</div>
</div>

templates/trick/_deleteModal.html.twig
{% if is_granted('IS_AUTHENTICATED_FULLY') %}
<div class="modal fade" id="modal_{{ trick.id }}" tabindex="-1" aria-labelledby="ModalLabel_{{ trick.id }}" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="ModalLabel_{{ trick.id }}">{{ trick.name }}</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>This action is irremediable, are you sure to delete <strong>{{ trick.name }}</strong>?</p>
      </div>
      <div class="modal-footer">
        <a href="{{ path('delete_trick', {'id': trick.id}) }}" type="button" class="btn btn-dark">Delete</a>
        <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Discard</button>
      </div>
    </div>
  </div>
</div>
{% endif %}

templates/trick/_deleteModifyButtons.html.twig
{% if is_granted('IS_AUTHENTICATED_FULLY') %}
    <div class="btn-group m-0" role="group">
        <button type="button" class="btn btn-sm btn-outline-secondary" data-bs-toggle="modal" data-bs-target="#modal_{{ trick.id }}">
            <img src="{{ asset("Style/img/trash-svgrepo-com.svg") }}" alt="pen icon" height="16"/>
        </button>
        <a href="{{ path('modify_trick', {'slug': trick.slug}) }}" class="btn btn-sm btn-outline-secondary">
            <img src="{{ asset("Style/img/pencil-svgrepo-com.svg") }}" alt="pen icon" height="16"/>
        </a>
    </div>
{% endif %}

templates/trick/_medias.html.twig
	<div class="col mb-2 text-center">
		{% if media.type == 'image' %}
			<img src={{ asset(images_directory ~ media.filename) }} class="bd-placeholder-img card-img-top" width="100%" height="200" alt="image"/>
		{% else %}
			<iframe width="100%" height="200" src="{{ media.filename }}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
		{% endif %}
		{% if app.request.attributes.get('_route') == 'modify_trick' or app.request.attributes.get('_route') == 'add_trick' %}
			{{ form_widget(trickForm.MainMedia.children[loop.index0], {'label': 'Set as main media'}) }}
			<a class="btn btn-danger my-2" href="{{ path('delete_media', {'id': media.id}) }}" data-delete data-token="{{ csrf_token('delete' ~ media.id) }}">Delete</a>
		{% endif %}
</div>

{% block jsDeleteImage %}
{% if app.request.attributes.get('_route') == 'modify_trick' or app.request.attributes.get('_route') == 'add_trick' %}
	<script>
		window.onload = () => {
			btnCancel = document.getElementById('btnCancel');
			let links = document.querySelectorAll("[data-delete]")
			for(link of links) {
				link.addEventListener("click", function(e){
					e.preventDefault()
					if(confirm('are you sure to delete this media?')) {
						fetch(this.getAttribute("href"), {
							method: "DELETE",
							headers: {
								"X-Requested-With": "XMLHttpRequest",
								"Content-type": "application/json"
							},
							body: JSON.stringify({"_token": this.dataset.token})
						}).then(
							response => response.json()
						).then(data => {
							if(data.success){
								this.parentElement.remove()
								btnCancel.remove();
							} else {
								alert(data.error)
							}
						})
					}
				})
			}
		}
	</script>
{% endif %}
{% endblock %}

templates/trick/_trickCard.html.twig
<div class="col" id="trick_{{ trick.id }}">
	<div class="card shadow-sm">
		{% if trick.mainMedia.type == 'image' %}
			{% set src = asset(images_directory ~ trick.mainMedia.filename) %}
		{% else %}
			{% if 'youtube' in trick.mainMedia.filename %}
				{% set src = "https://i3.ytimg.com/vi/" ~ trick.mainMedia.filename|trim('https://www.youtube.com/embed/') ~ "/hqdefault.jpg" %}
			{% endif %}
			{% if 'dailymotion' in trick.mainMedia.filename %}
				{% set src = "https://www.dailymotion.com/thumbnail/video/" ~ trick.mainMedia.filename|trim('https://www.dailymotion.com/embed/video/') %}
			{% endif %}
			{% if 'vimeo' in trick.mainMedia.filename %}
				{% set src = "https://vumbnail.com/" ~ trick.mainMedia.filename|trim('https://player.vimeo.com/video/') ~ ".jpg" %}
			{% endif %}
		{% endif %}
		<a href="{{ path('show_trick', {'slug': trick.slug}) }}">
			<img src={{ src }} class="bd-placeholder-img card-img-top img-fluid" width="100%" height="200" alt="image"/>
		</a>
			
		<div class="card-body">
			<div class="d-flex justify-content-between align-items-center col">
				<small class="text-muted">{{ trick.name }}</small>
					{{ include('trick/_deleteModifyButtons.html.twig') }}
			</div>
		</div>
	</div>
</div>

{{ include('trick/_deleteModal.html.twig') }}

templates/trick/addTrick.html.twig
 {% extends 'base.html.twig' %}
{% block stylesheet %}
<link href="{{ asset("Style/summernote/summernote-lite.min.css") }}" rel="stylesheet">

{% endblock %}

{% block javascript %}
  <script type="text/javascript" src="{{ asset("Style/js/jquery.js") }}"></script>
  <script type="text/javascript" src="{{ asset("Style/summernote/summernote-lite.min.js") }}"></script>
  <script type="text/javascript" src="{{ asset("Style/js/imagePreview.js") }}"></script>
  <script type="text/javascript" src="{{ asset("Style/js/transformTextArea.js") }}"></script>
  {% block jsDeleteImage %}{% endblock %}
{% endblock %}


 {% block body %}
 
 <main>
    <div class="album py-5 bg-light position-relative trickPage">
      <div class="container">
        <div class="row">
          <div class="col">
            <div class="card shadow-sm">
              <div class="card-body">
                <div class="justify-content-between align-items-center col">
                  <div class="justify-content-between align-items-center col">
                        {{ form_start(trickForm) }}
                    {% if trick is not defined %}
                      {% set trick = {name: '', description: '', group: {'id': '1'}} %}
                      {% set submitButtonText = 'Add trick' %}
                    {% else %}
                    
                      {% set submitButtonText = 'Modify trick' %}
                        <div class="row">
                        {% if trick.mainMedia.type == 'image' %}
                          <img src="{{ asset('/uploads/images/' ~ trick.mainMedia.filename) }}" alt="">
                        {% else %}
                          <iframe width="100%" height="780" src="{{ trick.mainMedia.filename }}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                        {% endif %}
                        </div>
                      <div class="d-flex row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-5 my-4">
                      
                        {% for media in trick.medias %}
                            {{ include('trick/_medias.html.twig') }}
                        {% endfor %}
                      </div>
                    {% endif %}
                    
                      <div class="d-flex row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-5 my-4 preview">
                      </div>
                      <div id="trick">
                      
                        {{ form_row(trickForm.name, {'value': trick.name}) }}
                        {% if trick.id is not defined %}
                        <p class='text-danger mb-0'>The first image uploaded will be set as main Image!</p>
                        {% endif %}
                        {{ form_row(trickForm.images) }}
                        <div class="mb-3">
                        <ul id="video-fields-list"
                            style="list-style: none;"
                            data-prototype="{{ form_widget(trickForm.videos.vars.prototype)|e }}"
                            data-widget-tags="{{ '<li></li>'|e }}"
                            data-widget-counter="{{ trickForm.videos|length }}">
                          {% for video in trickForm.videos %}
                            <li class="mb-3">{{ form_widget(video) }}</li>
                          {% endfor %}
                        </ul>
                        <button type="button" class="add-another-collection-widget btn btn-dark" data-list-selector="#video-fields-list">Add another video</button>
                        </div>
                        {{ form_row(trickForm.description, {'value': trick.description}) }}
                        {{ form_row(trickForm.group, {'value': trick.group.id}) }}
                        <div class="buttons row mb-3">
                          <div class="btn-group justify-content-center">
                          <p class="mx-2">{{ form_widget(trickForm.Create_Trick, {'label': submitButtonText}) }}</p>
                          <p><a href="{{ relative_path(app.request.headers.get('referer')) }}" class="btn btn-danger" id="btnCancel">Cancel</a></p>
                          </div>
                        </div>
                        {{ form_end(trickForm) }}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  </main>
{% endblock %}

templates/trick/trick.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello TrickController!{% endblock %}


{% block javascript %}
<script language = "javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script> 
{% include('js/_loadMoreCommentary.js.twig') %}
{% endblock %}

{% block body %}
 <main>
    <div class="album py-5 bg-light position-relative trickPage">
      <div class="container">
        <div class="row">
          <div class="col">
            <div class="card shadow-sm">
              <div class="card-body">
                {{ include('trick/_deleteModal.html.twig') }}
                <div class="row mb-2">
                  <div class="col">
                    <h1>{{ trick.name }}</h1>
                  </div>
                  <div class="col text-end">
                    {{ include('trick/_deleteModifyButtons.html.twig') }}
                  </div>
                </div>
                <div class="justify-content-between align-items-center col">
                  <div class="justify-content-between align-items-center col">
                  <div class="row">
                        {% if trick.mainMedia.type == 'image' %}
                          <img src="{{ asset(images_directory ~ trick.mainMedia.filename) }}" alt="">
                        {% else %}
                          <iframe width="100%" height="780" src="{{ trick.mainMedia.filename }}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                        {% endif %}
                  </div>
                  <div class="d-flex row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-5 my-4">
                  {% for media in trick.medias|filter( v => v != trick.mainMedia) %}
                    {{ include('trick/_medias.html.twig') }}
                  {% endfor %}
                  </div>
                    <div class="row" style="padding: 10px;">
                      
                      <p>{{ trick.description|raw }}</p>
                    </div>
                    <div class="row">
                      <div class="d-inline-flex justify-content-center">
                        <h4 class="mx-3">Created <span class="badge bg-secondary col">{{ trick.publishedDate|date('Y-m-d') }}</span></h4>
                        <h4 class="mx-3">By <span class="badge bg-secondary col">{{ trick.user.username }}</span></h4>
                        <h4 class="mx-3">In group <span class="badge bg-secondary col">{{ trick.group.name }}</span></h4>
                        <h4 class="mx-3">Last update <span class="badge bg-secondary col">
                        {% if trick.lastUpdated is null %}
                          Never
                        {% else %}  
                          {{ trick.lastUpdated|date('Y-m-d') }}
                        {% endif %}                          
                        </span></h4>
                      </div>
                    </div>
                    <hr>
                    {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                      <div class="row">
                        {{ form(commentaryForm) }}
                          <script type="text/javascript">
                            textarea = document.querySelector("#{{ commentaryForm.commentary.vars.id }}");
                            textarea.addEventListener('input', autoResize, false);
                          
                            function autoResize() {
                                this.style.height = 'auto';
                                this.style.height = this.scrollHeight + 'px';
                            }
                          </script>
                      </div>
                      <hr>
                    {% endif %}
                    <div id="commentarys" class="mb-5">
                    
                    {% for commentary in commentarys %}
                      {{ include('trick/_commentarys.html.twig') }}
                    {% endfor %}
                    </div>
                  </div>
                  <div class="row">
                  <button onClick="loadMore()" class="btn btn-dark my-3 position-absolute bottom-0 start-50 translate-middle-x" id="loadMore">Load More</button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  </main>

{% endblock %}

templates/trick/tricks.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello TrickController!
{% endblock %}

{% block javascript %}
<script language = "javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script> 
{% include('js/_loadMoreTricks.js.twig') %}
{% endblock %}

{% block body %}

	<main>

		<div class="hero p-0 m-0">
			<h1 class="slogan d-inline">The snow must go on</h1>
			<a href="#tricks">
				<div class="arrow_container">
					<div class="chevron"></div>
					<div class="chevron"></div>
					<div class="chevron"></div>
				</div>
			</a>
		</div>

		<div class="album py-5 bg-light position-relative" id="tricks">
			<div class="container">

				<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-5 g-3 mb-3" id="tricksCards">

					{% for trick in tricks %}
						{{ include('trick/_trickCard.html.twig') }}
					{% endfor %}
					
				</div>
				<div class="text-center">
					<button onClick="loadMore()" class="btn btn-dark my-3" id="loadMore">Load More</button>
					{% if is_granted('IS_AUTHENTICATED_FULLY') %}
					<a href="{{ path('add_trick') }}" class="btn btn-dark my-3">Add a trick</a>
					{% endif %}
				</div>
				<a href="#tricks" id="downArrow">
					<div class="arrow_container">
						<div class="chevron2"></div>
						<div class="chevron2"></div>
						<div class="chevron2"></div>
					</div>
				</a>
			</div>
		</div>
	</main>

	{% endblock %}